base task
alexzaslavsky/CrmWebApi pull request #1
Opened 2021-12-23 15:44 UTC by alexzaslavsky

db connection
controller

2021-12-23 15:58 UTC, demchuknick6 commented
please rename PR to format '[ticketName] Change description'

2021-12-23 16:11 UTC, demchuknick6 requested changes

2021-12-23 16:11 UTC, demchuknick6 commented on CrmWebApi.Domain.DatabaseContext/DatabaseContext.cs
> +            Database.EnsureCreated();
no need to delete database every time you start your application

2021-12-23 16:11 UTC, demchuknick6 commented on CrmWebApi.Domain.DatabaseContext/DatabaseContext.cs
> +                });
this can be moved to a separate Seeding class. also, don't forget to call `base.OnModelCreating(modelBuilder);`

2021-12-23 16:11 UTC, demchuknick6 commented on CrmWebApi.Domain.DatabaseContext/Migrations/20211223150705_CreateProductTable.cs
> +                    Name = table.Column<string>(type: "nvarchar(max)", nullable: true),
are you sure column Name should be nullable?

2021-12-23 16:11 UTC, demchuknick6 commented on CrmWebApi.Domain.DatabaseContext/Migrations/20211223150705_CreateProductTable.cs
> +                    Name = table.Column<string>(type: "nvarchar(max)", nullable: true),
also, you can limit "nvarchar(max)" to "nvarchar(128)" for example. Please read about EF Fluent Api, and apply some configuration on your entities.

2021-12-23 16:11 UTC, demchuknick6 commented on CrmWebApi.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Domain", "Domain", "{DD0CEECA-E1A7-4C80-84F0-7D3720781771}"
maybe `CrmWebApi.Domain`? all projects should start with a common prefix

2021-12-23 16:11 UTC, demchuknick6 commented on CrmWebApi/Controllers/ProductsController.cs
> +        public ProductsController(DatabaseContext databaseContext)
please add extra line between a field and a constructor

2021-12-23 16:11 UTC, demchuknick6 commented on CrmWebApi/Startup.cs
> +            string connection = Configuration.GetConnectionString("DefaultConnection");
use var. also, create a static Constants class and add a field `const string ConnectionStringKey = "DefaultConnection"`
then use `var connection = Configuration.GetConnectionString(Constants.ConnectionStringKey);`

2021-12-23 18:16 UTC, alexzaslavsky commented on CrmWebApi/Controllers/ProductsController.cs
> +        public ProductsController(DatabaseContext databaseContext)
![image](https://user-images.githubusercontent.com/32812666/147278181-315bd4b7-d47c-41fc-aa74-5b595125487e.png)

2021-12-23 18:17 UTC, alexzaslavsky commented on CrmWebApi/Controllers/ProductsController.cs
> +        public ProductsController(DatabaseContext databaseContext)
this link tricked my sight :)

2021-12-24 13:05 UTC, demchuknick6 approved these changes

2021-12-24 13:13 UTC, alexzaslavsky commented on CrmWebApi.Domain.DatabaseContext/Migrations/20211224120443_ProductNameLessSymbols.cs
> +    public partial class ProductNameLessSymbols : Migration
I did some research using them :)

2021-12-24 13:22 UTC, alexzaslavsky commented on CrmWebApi.Domain.DatabaseContext/DatabaseContext.cs
> +        public DatabaseContext() {}
Looks like I don't really need it. Somehow it was fixed)
Gonna remove it.

2021-12-25 10:57 UTC, merged