[ABC-002] : Extended ProductController
alexzaslavsky/CrmWebApi pull request #2
Opened 2021-12-28 09:28 UTC by alexzaslavsky

Added ProductCategory entity
Used Repository pattern
Fluent API for entity configuration

2021-12-28 10:34 UTC, demchuknick6 requested changes

2021-12-28 10:34 UTC, demchuknick6 commented on CrmWebApi.Domain.DatabaseContext/DatabaseContext.cs
> +            ProductConfiguration(modelBuilder);
it is not obvious what ProductConfiguration() method does... consider using `modelBuilder.ApplyConfiguration(new ProductConfiguration);`

2021-12-28 10:34 UTC, demchuknick6 commented on CrmWebApi.Domain.DatabaseContext/DatabaseContext.cs
> +        }
create a separate folder Configurations and add configuration classes there like: `class ProductConfiguration : IEntityTypeConfiguration<Product>`
remember about single responsibility principle

2021-12-28 10:34 UTC, demchuknick6 commented on CrmWebApi.Domain.DatabaseContext/Extensions/ModelBuilderExtensions.cs
> +                    new Product { Id = 5, Name = "Oppo A74", Price = 8900, CategoryId = 1, IsAvailable = true }
change seeding so that every category has at least one product

2021-12-28 10:34 UTC, demchuknick6 commented on CrmWebApi/Services/ProductRepository.cs
> +        public IEnumerable<ProductDto> GetAll()
add empty line here

2021-12-28 10:34 UTC, demchuknick6 commented on CrmWebApi/Controllers/ProductsController.cs
> +        public IEnumerable<ProductDto> Get()
it's great that you've decided to use ProductDto model here but for this task it's fine to use your domain model Product.

2021-12-28 10:34 UTC, demchuknick6 commented on CrmWebApi/Interfaces/IProductRepository.cs
> +        IEnumerable<ProductDto> GetAll();
the repository is a data access level so it should be IEnumerable<Product> GetAll();

2021-12-28 10:34 UTC, demchuknick6 commented on CrmWebApi/Services/ProductRepository.cs
> +            });
for now, use `return _databaseContext.Products.ToList();`, but we will change that in the future

2021-12-28 10:34 UTC, demchuknick6 commented on CrmWebApi/Services/ProductRepository.cs
> +                .OrderByDescending(c => c.Products.Count).FirstOrDefault()?.Name;
this code looks great, but in the ProductRepository you can only use Products table, so please update your linq to get the category name via Products table and categoryId FK. I know it is better to create CategoryRepository, but let's assume you have such a weird task))

2021-12-28 10:34 UTC, demchuknick6 commented on CrmWebApi/Services/ProductRepository.cs
> +namespace CrmWebApi.Services
change namespace to CrmWebApi.Repositories

2021-12-29 10:15 UTC, demchuknick6 commented on CrmWebApi/Startup.cs
> +using System.Text.Json.Serialization;
don't forget to remove unused references

2021-12-29 10:16 UTC, demchuknick6 commented on CrmWebApi.Domain.DatabaseContext/DatabaseContext.cs
> +            modelBuilder.ApplyConfiguration(new ProductCategoryConfiguration());
well done here

2021-12-29 10:18 UTC, demchuknick6 commented on CrmWebApi/Repositories/ProductRepository.cs
> +            return _databaseContext.Products.ToList()
remove .ToList() here

2021-12-29 10:19 UTC, demchuknick6 commented on CrmWebApi/Repositories/ProductRepository.cs
> +                .Select(group => new {CategoryName = group.FirstOrDefault()?.Category.Name, Count = group.Count()})
try smth like .GroupBy(g => g.Category.Name).Select(s => new { Key = s.Key, Count = s.Count() })

2021-12-29 10:19 UTC, demchuknick6 commented on CrmWebApi/Repositories/ProductRepository.cs
> +                .FirstOrDefault()?.CategoryName;
.FirstOrDefault()?.Key?

2021-12-29 10:22 UTC, demchuknick6 commented
fix comments and add unit tests for product repository

2022-01-04 08:58 UTC, demchuknick6 approved these changes

2022-01-04 08:58 UTC, demchuknick6 commented on CrmWebApi.Tests/ProductRepositoryTests.cs
> +                .AddRange(new List<ProductCategory> { smartphone, laptop, tv });
is it possible to add ProductCategory[] array instead of list here?

2022-01-04 08:58 UTC, demchuknick6 commented on CrmWebApi.Tests/ProductRepositoryTests.cs
> +        }
well done here!

2022-01-04 08:58 UTC, demchuknick6 commented on CrmWebApi.Tests/ProductRepositoryTests.cs
> +        {
please rename all tests in this class to be named MethodName_expected_behavior_condition, for example GetAll_returns_eight_products_when_eight_products_exist_in_database

2022-01-04 09:03 UTC, demchuknick6 commented on CrmWebApi.Domain.DatabaseContext/Configurations/ProductCategoryConfiguration.cs
> +        }
is this method used anywhere? I see another method Seed in this class that has exactly the same logic

2022-01-04 09:05 UTC, demchuknick6 commented on CrmWebApi.Tests/ProductRepositoryTests.cs
> +namespace CrmWebApi.Tests
move this class to CrmWebApi.Tests.Repositories

2022-01-04 09:13 UTC, demchuknick6 commented
fix comments and merge this PR, then contact me for the next task

2022-01-04 09:51 UTC, alexzaslavsky commented on CrmWebApi.Domain.DatabaseContext/Configurations/ProductCategoryConfiguration.cs
> +        }
Yeah, I forgot to remove this and call ConfigureProperties and Seed here

2022-01-04 10:08 UTC, demchuknick6 commented on CrmWebApi.Tests/Repositories/ProductRepositoryTests.cs
> +                    new Product { Id = 2, Name = "IPhone 13 Pro", Price = 39000, CategoryId = 1, Category = smartphone },
array here?

2022-01-04 10:08 UTC, demchuknick6 commented on CrmWebApi.Tests/Repositories/ProductRepositoryTests.cs
> +                "IPhone 13 Pro",
and here?

2022-01-04 10:22 UTC, merged